core/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

funcionarios/urls.py
from django.urls import path
from .views import (
    FuncionariosList,
    FuncionarioEdit,
    FuncionarioDelete,
    FuncionarioNovo
)

urlpatterns = [
    path('', FuncionariosList.as_view(), name= 'list_funcionarios'),
    path('novo/', FuncionarioNovo.as_view(), name= 'create_funcionario'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name= 'update_funcionario'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name= 'delete_funcionario'),
]

gestao_fit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('empresa/', include('empresas.urls')),
    path('documento/', include('documentos.urls')),
    path('horas-extras/', include('registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documentos/models.py
from django.db import models
from django.shortcuts import reverse

from funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from departamentos.models import Departamento
from empresas.models import Empresa

class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.PROTECT, null=True, blank=True) #permite em branco

    def get_absolute_url(self):
        return reverse('list_funcionarios')
    def __str__(self):
        return self.nome

funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView,
    CreateView
)
from .models import Funcionario


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)

class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')

class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base_tela.html'%}

{% block 'dashboard'%}

Delete

<form method="POST">

    {% csrf_token %}
    <h1>Voce está certo que quer deletar {{ object }}</h1>
    {{ form }}

    <button type="submit" class="btn btn-danger">Confirmar</button>


</form>
{% endblock %}

funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base_tela.html'%}

{% block 'dashboard'%}


{{ object }}
<form method="POST">

    {% csrf_token %}

    {{ form }}

    <button type="submit" class="btn btn-main">Salvar</button>


</form>
<br>

<a href="{% url 'create_documento' object.id %}" class="btn btn-success">
    Adicionar documento
</a>

{% for documento in object.documento_set.all%}

    <a href="{{ documento.arquivo.url }} "> {{ documento.descricao }}  </a><br>

{% endfor %}
{% endblock %}

funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base_tela.html' %}

{% block 'dashboard' %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="text-white">Nome</th>
                    <th class="text-white">Departamento</th>
                    <th class="text-white">Empresa</th>
                    <th class="text-white">Deletar</th>
                    <th class="text-white">Novo</th>
                </tr>
            </thead>
             <tbody>
            {% for funcionario in object_list %}
                {% for departamento in funcionario.departamentos.all %}
                <tr>
                    {% if forloop.first %}
                        <td class="text-white" rowspan="{{ funcionario.departamentos.count }}"><a href="{% url 'update_funcionario' funcionario.id %}">{{ funcionario }}</a></td>
                    {% endif %}
                    <td class="text-white">{{ departamento.nome }}</td>
                    <td class="text-white">{{ funcionario.empresa }}</td>
                    <td><a href="{% url 'delete_funcionario' funcionario.id %}">Deletar</a></td>
                    <td><a href="{% url 'create_funcionario' %}" class="btn btn-info">Novo</a></td>
                </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}